//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BridgeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BridgeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bridge.Resources.Languages.BridgeStrings", typeof(BridgeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchaser / Advisor.
        /// </summary>
        internal static string Advisor {
            get {
                return ResourceManager.GetString("Advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the terms and conditions.
        /// </summary>
        internal static string AgreeValidation {
            get {
                return ResourceManager.GetString("AgreeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want change password?.
        /// </summary>
        internal static string ChangePasswordConfirmation {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete My Account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want delete account?.
        /// </summary>
        internal static string DeleteAccountConfirmation {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is already taken.
        /// </summary>
        internal static string EmailTaken {
            get {
                return ResourceManager.GetString("EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Failed..
        /// </summary>
        internal static string FailedChangePassword {
            get {
                return ResourceManager.GetString("FailedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Delete Failed!.
        /// </summary>
        internal static string FailedDeleteAccount {
            get {
                return ResourceManager.GetString("FailedDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Failed, Please Try Again.
        /// </summary>
        internal static string FailRegisteration {
            get {
                return ResourceManager.GetString("FailRegisteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fliter &amp; Sort.
        /// </summary>
        internal static string FilterSort {
            get {
                return ResourceManager.GetString("FilterSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Transaction.
        /// </summary>
        internal static string FilterTransaction {
            get {
                return ResourceManager.GetString("FilterTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong please try again.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Login..
        /// </summary>
        internal static string HeaderLogin1 {
            get {
                return ResourceManager.GetString("HeaderLogin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have an account?.
        /// </summary>
        internal static string HeaderLogin2 {
            get {
                return ResourceManager.GetString("HeaderLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Right Address To Find The Best Product.
        /// </summary>
        internal static string HeaderOnboard1 {
            get {
                return ResourceManager.GetString("HeaderOnboard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is now very easy to reach the best quality among all the products on the internet!.
        /// </summary>
        internal static string HeaderOnboard2 {
            get {
                return ResourceManager.GetString("HeaderOnboard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Register..
        /// </summary>
        internal static string HeaderRegister1 {
            get {
                return ResourceManager.GetString("HeaderRegister1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an account?.
        /// </summary>
        internal static string HeaderRegister2 {
            get {
                return ResourceManager.GetString("HeaderRegister2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Doesn&apos;t Match.
        /// </summary>
        internal static string InvalidConfirmPassword {
            get {
                return ResourceManager.GetString("InvalidConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 8 letters.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i have agreed to the .
        /// </summary>
        internal static string lbTerms1 {
            get {
                return ResourceManager.GetString("lbTerms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms and conditions.
        /// </summary>
        internal static string lbTerms2 {
            get {
                return ResourceManager.GetString("lbTerms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not Approved yet..
        /// </summary>
        internal static string LoginApproval {
            get {
                return ResourceManager.GetString("LoginApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by fingerprint.
        /// </summary>
        internal static string LoginFinger {
            get {
                return ResourceManager.GetString("LoginFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want logout?.
        /// </summary>
        internal static string LogoutConfirmation {
            get {
                return ResourceManager.GetString("LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifcations.
        /// </summary>
        internal static string Notifcations {
            get {
                return ResourceManager.GetString("Notifcations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        internal static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend.
        /// </summary>
        internal static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Store.
        /// </summary>
        internal static string RetailStore {
            get {
                return ResourceManager.GetString("RetailStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Store Name.
        /// </summary>
        internal static string RetailStoreName {
            get {
                return ResourceManager.GetString("RetailStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan product code.
        /// </summary>
        internal static string ScanProduct {
            get {
                return ResourceManager.GetString("ScanProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Qr Code.
        /// </summary>
        internal static string ScanQR {
            get {
                return ResourceManager.GetString("ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for?.
        /// </summary>
        internal static string SearchText1 {
            get {
                return ResourceManager.GetString("SearchText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account Type.
        /// </summary>
        internal static string SelectAccountType {
            get {
                return ResourceManager.GetString("SelectAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Products.
        /// </summary>
        internal static string ShowProducts {
            get {
                return ResourceManager.GetString("ShowProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results.
        /// </summary>
        internal static string ShowResults {
            get {
                return ResourceManager.GetString("ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions.
        /// </summary>
        internal static string SpecialInstructions {
            get {
                return ResourceManager.GetString("SpecialInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        internal static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully, please login with your new password..
        /// </summary>
        internal static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Deleted Successfully!.
        /// </summary>
        internal static string SuccessDeleteAccount {
            get {
                return ResourceManager.GetString("SuccessDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered, approval is pending..
        /// </summary>
        internal static string SuccessRegisteration {
            get {
                return ResourceManager.GetString("SuccessRegisteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتفاقية الاستخدام
        ///اتفاقية شروط استخدام موقع وتطبيق Bridge
        ///أهلا بك إلى موقع وتطبيق Bridge. باستعمالك لهذا (الموقع او التطبيق)، فإنك توافق على أن تتقيد وتلتزم بالشروط والأحكام التالية لذا، يرجى منك الاطلاع على هذه الأحكام بدقة. أن كنت لا توافق على هذه الأحكام، فعليك ألا تتطلع على المعلومات المتوفرة في (الموقع او التطبيق).
        ///
        ///1. قبول الاتفاقية: أنت تتعهد بقبول الشروط والأحكام الواردة في هذه الاتفاقية (&quot;الاتفاقية&quot;) فيما يتعلق بموقع www.jo-bridge.com (&quot;(الموقع او التطبيق)&quot;). تشكل هذه الاتفاقية كامل الاتفاق بين [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have agreed to the.
        /// </summary>
        internal static string TermsText1 {
            get {
                return ResourceManager.GetString("TermsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms &amp; conditions.
        /// </summary>
        internal static string TermsText2 {
            get {
                return ResourceManager.GetString("TermsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points.
        /// </summary>
        internal static string TotalPoints {
            get {
                return ResourceManager.GetString("TotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will be deactivated until your updates are approved by our team.
        /// </summary>
        internal static string UpdateAccount {
            get {
                return ResourceManager.GetString("UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for updating your data..
        /// </summary>
        internal static string UpdateAccount2 {
            get {
                return ResourceManager.GetString("UpdateAccount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Information was Failed..
        /// </summary>
        internal static string UpdateAccount3 {
            get {
                return ResourceManager.GetString("UpdateAccount3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill All Fields.
        /// </summary>
        internal static string Validation1 {
            get {
                return ResourceManager.GetString("Validation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
